# SPDX-FileCopyrightText: 2025 Alexander Wietek <awietek@pks.mpg.de>
#
# SPDX-License-Identifier: Apache-2.0

name = "XDiag"
uuid = "3edaab83-692e-476a-bab5-541af84d25fc"
authors = ["Alex Wietek <awietek@pks.mpg.de> and contributors"]
version = "0.4.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
XDiag_jll = "05e47fe5-458f-5313-a276-ec18ac0ef94c"

[compat]
CxxWrap = "0.17"
Printf = "1.0.0"
XDiag_jll = "=0.4.0"
julia = "1.7"
LinearAlgebra = "1" 

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
